spring:
  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:C:/Users/LavdimKrasniqi/test;AUTO_SERVER=TRUE

    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
      platform: h2
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
  application:
    name: Bank System
